### ISSUE TITLE
BIND button in Flight mode

### ISSUE THREAD

**Issue by ajjjjjjjj** [OpenI6X/opentx#146]
**Describe the bug**
After exiting edit mode, moving to next value using BIND button increases field value at the same time.

**To Reproduce**
1. Go to Flight modes
2. Click on FM0
3. Scroll down to Trims
4. Edit trim value (OK), exit edit mode (CANCEL)
5. Moving to next value using BIND button increases field value at the same time.

**Expected behavior**
After exiting edit mode BIND button should not increase value.

**Comment by jakeeri** [comment]
If you select the next/previous value with right pot it doesn't increment the value in the field.
Also if you change the value in the field with left pot, it does change without pressing OK (edit) first.

**Comment by ajjjjjjjj** [comment]
Also after moving with BIND it can be corrected using DOWN button, so not critical but it's there.
