### ISSUE TITLE
sm100 Cable does not work

### ISSUE THREAD

**Issue by DuckyScr** [OpenI6X/opentx#151]
Hello, I have bought sim cable sm100 and plugged that to my computer and radio and it havent worked. I thaink that the radio does not send any signal to the port so can someone help me with setting that up?

**Comment by jakeeri** [comment]
Sim cable doesn't work. You need a cable which came with the transmitter, if it did. Unfortunately that cable is not in every box for some reason.

**Comment by jakeeri** [comment]
Data cable for flashing look like this.
![image](https://user-images.githubusercontent.com/66841741/153013625-ae182ceb-1e27-4ba4-a9c4-6d3f5bd85114.jpeg)

**Comment by Ragi42DEV** [comment]
but if i would solder tx2 to s video connector ppm pin and enable external RF to PPM it should work. Shouldn't it?

**Comment by ajjjjjjjj** [comment]
What do you want to use that cable? Standard cable (USB) allows for joystick, backup and flashing.

**Comment by zxh465118755** [comment]
I seem to have the same problem as you。flysky i6X opentx，PPM Abnormal operation，No export PPM

**Comment by ajjjjjjjj** [comment]
So true issue here is PPM output, described currently here: https://github.com/OpenI6X/opentx/issues/283
Therefore I'm closing this one and let's keep PPM discussion there.
