### ISSUE TITLE
USB Joystick reboots

### ISSUE THREAD

**Issue by xpertcrush** [OpenI6X/opentx#152]
**Describe the bug**
When i connect usb as joystick it doesn't work on first go and tx also restarts on connection, on windows after trying 2-3 times it connects but in setup joystick option, none of the axis works, see video for demo.

**To Reproduce**
1. Go to setup and change usb to once
2. Connect to pc using data cable
3. It won't connect and you will only see usb input device,
Repeat the steps, your tx may reboot on own and it will connect, but your current model selected will have garbled name and settings inside.

**Expected behavior**
It should work on first go and there should be no reboots

**Screenshots**
![P_20220214_001451.jpg](https://user-images.githubusercontent.com/67045883/153791027-3b1dc468-bf9c-44e0-ac24-a460c8b3fec1.jpg)

![P_20220214_001505.jpg](https://user-images.githubusercontent.com/67045883/153791083-b5571eea-7d42-4b24-a3a6-5973f732d889.jpg)

https://youtu.be/cawFnemfd7o

**General information**
 - OpenTX version (e.g. 1.3.0 )
 - Hardware (e.g. Flysky i6x)

**Comment by ajjjjjjjj** [comment]
Can you retry on this build?
[openi6x-usbtest.zip](https://github.com/OpenI6X/opentx/files/8062914/openi6x-usbtest.zip)

**Comment by xpertcrush** [comment]
Yes i can, wait i will do it now and report back

**Comment by xpertcrush** [comment]
> Can you retry on this build? You should manually  format eeprom after flashing it.
> [openi6x-usbtest.zip](https://github.com/OpenI6X/opentx/files/8062914/openi6x-usbtest.zip)
> 
> 

Initially expression:

Looks good so far it didn't rebooted and my sticked detected as well ![P_20220215_110145.jpg](https://user-images.githubusercontent.com/67045883/153998693-16cc4877-b5da-4174-bf02-7b988898c068.jpg)

![P_20220215_110155.jpg](https://user-images.githubusercontent.com/67045883/153998708-c7cd2441-2dc8-49a9-b011-e4b7e9484c85.jpg)

Please change batter low range from 3.5

![P_20220215_110230.jpg](https://user-images.githubusercontent.com/67045883/153998828-a52da0f2-3046-421a-9484-d472a6fb011d.jpg)


So i dont hear this continuous beep of low battery on lipo

![P_20220215_110245.jpg](https://user-images.githubusercontent.com/67045883/153998864-25d94a34-e846-46c4-9e24-cadca18914a6.jpg)

**Comment by xpertcrush** [comment]
Unfortunately It's back again today


https://youtu.be/elJ7mrpUN3A

**Comment by marianomd** [comment]
Should we try disabling the watchdog to see if its a delay or a lockup?

**Comment by ajjjjjjjj** [comment]
Can you share your eeprom copy?

**Comment by ajjjjjjjj** [comment]
@xpertcrush , maybe i found the fix, try it:
[opentx-i6x-dev-wdg.zip](https://github.com/OpenI6X/opentx/files/8383831/opentx-i6x-dev-wdg.zip)

**Comment by ajjjjjjjj** [comment]
Closing because stalled

**Comment by marianomd** [comment]
Still happening on 1.6.1. Will try to debug it (through bluetooth serial💪)

**Comment by marianomd** [comment]
It seems related to USB cable quality.

**Comment by marianomd** [comment]
The throttle warning doesn't appear during the bootloops.

https://user-images.githubusercontent.com/274989/172937311-857c1803-8134-447e-afa5-7d77a5330c04.mp4

.

**Comment by Pmant** [comment]
I have a similar issue, never got joystick mode to work. However, flashing via dfu mode and storage mode do work. 
In joystick mode I get a broken device (Code 10) in windows and the i6x randomly beeps a couple times.

**Comment by througer** [comment]
Hello, great work so far. The joystick mode does never work for me in version 1.6.0 or 1.6.1. Tried the older versions. Had to flash back to Version 1.1.0. This will do it every 4th or 5th attempt. In very few cases, the device restarts. Most of the time, an error code 10 appears in the device-manager.

**Comment by DocTrucker** [comment]
Just updated from the one of the early versions of this that had to be flashed by ST Link Adaptor. Flashed fine by DFU and USB cable on linux. Booted into windows (for simulator) and the Devices and Printers page shows "FS-i6x Joystick" but the hardware tab of the properties shows "Device Status: This device cannot start. (Code 10)"

Version 1.8.0 2022-11-04

**Comment by woodprop** [comment]
In version 1.9.0 USB Joystick works fine for me! (in 1.8.0 it was always rebooting). 
only in one case I have my radio rebooted itself - if I set USB mode to joystick, connect the radio to PC, then unplug it and plug in again without powering off the radio. But it is not a big deal...

**Comment by ajjjjjjjj** [comment]
Fixed by #424
