### ISSUE TITLE
Wrong channel order

### ISSUE THREAD

**Issue by WAUrb** [OpenI6X/opentx#154]
OPENi6X is quite good, except I can't put the channels in right order. To have them right in mode 1 I have to select mode 4, but then all input are reversed (no big thing) and trims are swapped Throttle/elevator, rudder/aileron

**Comment by WAUrb** [comment]
Found the solution! I swapped the two sticks connectors and now it works fine. Why they were reversed (I didn't remember doing it myself) and why it worked fine with its original firmware is a mistery!
Openi6X is a beautiful mod, especially if you already own an OpenTX tx (in my case TX16) or you are foresseeing buying one.

**Comment by ajjjjjjjj** [comment]
I'm glad that you solved it.
