### ISSUE TITLE
openi6X PPM  Not working properly

### ISSUE THREAD

**Issue by zxh465118755** [OpenI6X/opentx#155]
**Describe the bug**

I've opened it openi6X External RF  PPM, but openi6X PPM  Not working properly.
PPM-out and TX2 welded on the motherboard have been tried。
There is no signal output。

Moreover, when I have two models, if I switch from mode 1 to mode 2, I will still be in mode 1 after shutdown and restart. If I want to use mode 2, I can only switch from mode 1 to mode 2 and then switch to mode 1 again. Shutdown and restart at this time is mode 2

**Screenshots**
![IMG_2487](https://user-images.githubusercontent.com/35945094/154023673-9f8398ad-6bb2-47e2-aa4b-86a70d13a9eb.JPG)

![IMG_2488](https://user-images.githubusercontent.com/35945094/154024149-da728f4e-3c71-42c4-a0a2-1df85b1144cf.JPG)

![IMG_2502](https://user-images.githubusercontent.com/35945094/154024167-a66f8cf4-cbe3-4814-a017-2aa29a967260.JPG)
![IMG_2503](https://user-images.githubusercontent.com/35945094/154024189-4ebaca82-44da-4cca-a728-9553115200a6.JPG)
![IMG_2490](https://user-images.githubusercontent.com/35945094/154024201-807ea441-d29d-421d-9a0e-2c4110895e20.JPG)
![IMG_2504](https://user-images.githubusercontent.com/35945094/154024208-9a559efc-872e-408e-bc41-8677472a3df7.JPG)
![IMG_2505](https://user-images.githubusercontent.com/35945094/154024230-41abcaf3-fee8-4e6b-927b-a73b8a573a63.JPG)

General information

OpenTX version (openi6x-1.3.0 )
Hardware (Flysky i6x)

**Comment by tn2009** [comment]
confirm. changes are not saved immediately.

**Comment by zxh465118755** [comment]
The switching model can figure out how to operate, but the PPM output still doesn't work. The PPM output can be used only when the model without the PPM mode is switched back to the PPM model. If the model with the PPM mode is directly switched on, PPM has no response

**Comment by zxh465118755** [comment]
I found some rules. If I turn off the PPM, press the return button for a long time to turn it off, and then turn on the PPM mode after restarting, the remote control will have ppm out. However, if I turn off and restart again, even if the ppm is on, there is still no ppm out

**Comment by xpertcrush** [comment]
> I apologize for the off-topic question, but 7.9V? what source to power?

2s li ion/lipo

**Comment by tn2009** [comment]
> > I apologize for the off-topic question, but 7.9V? what source to power?
> 
> 2s li ion/lipo

a maximum of 6 volts will otherwise burn out.

**Comment by ajjjjjjjj** [comment]
@zxh465118755 , do you read readme on main page and/or release notes on how to be sure that settings are stored?

**Comment by rakesh-i** [comment]
> > > I apologize for the off-topic question, but 7.9V? what source to power?
> > 
> > 
> > 2s li ion/lipo
> 
> a maximum of 6 volts will otherwise burn out.
![IMG_20220218_190259](https://user-images.githubusercontent.com/57840815/154693017-6ab45948-1a9f-4721-9293-339cda31f50e.jpg)
I have been using 2 800mah 14500 li-ion batteries for a month now. The balance connector to charge them.
![IMG_20220218_190731](https://user-images.githubusercontent.com/57840815/154693072-d270bbc2-29f5-4eca-ae76-5a73ea87ec8e.jpg)
This is the voltage range i have set.
![IMG_20220218_190337](https://user-images.githubusercontent.com/57840815/154693082-050769c3-ff98-4c52-97b5-0cd643c39f88.jpg)
Low battery voltage. I'm getting 4 and a half hours of flying and 6 hours of simulator with internal RF turned off.  
![IMG_20220218_190350](https://user-images.githubusercontent.com/57840815/154693047-3a81dcb5-f48f-4d82-98a8-6c0d18e87916.jpg)
Best modification i have made so far. There is a voltage regulator and voltage divider on the input side  so, no worry of burning the chip. Don't do this on fs-i6 as it does not have voltage divider which supports higher voltages. (try it at you own risk)

**Comment by zxh465118755** [comment]
> @zxh465118755 , do you read readme on main page and/or release notes on how to be sure that settings are stored?

[](https://fanyi.baidu.com/###)[](javascript:void(0);)很抱歉我没有注意到说明
I'm sorry I didn't notice the release notes，I used the correct shutdown method and the problem was solved，However, there are still problems with ppm output. You can only turn on ppm without turning on ppm, and then turn on ppm. Ppmout will not work normally after restart，Sorry again for my blindness。Sorry again for my stupidity

**Comment by Andikaluku** [comment]
Bad ppm
