### ISSUE TITLE
Telemetry menu and display

### ISSUE THREAD

**Issue by tn2009** [OpenI6X/opentx#158]
A choice of 8 sensors is available in the telemetry menu. There are only 6 sensors on the screen.

![20220216_140550](https://user-images.githubusercontent.com/12898858/154243392-b4bcdf1b-b102-46a9-9e9c-15aeba89be8a.jpg)
![20220216_140242](https://user-images.githubusercontent.com/12898858/154243420-28bf122a-2f25-482f-bac1-e36773f879f6.jpg)
 Firmware 1.3.0

**Comment by megacct** [comment]
values for 7 and 8 will appear where 'NO DATA' is in your screenshot when data is available

**Comment by tn2009** [comment]
> values for 7 and 8 will appear where 'NO DATA' is in your screenshot when data is available
Only 6.
![20220216_145350](https://user-images.githubusercontent.com/12898858/154250142-093b6970-2ac7-42cd-82fd-c440de20deba.jpg)

**Comment by megacct** [comment]
What sources have you set for items 7 and 8?

**Comment by megacct** [comment]
Certainly works in version 1.1.1
![20220216_110220](https://user-images.githubusercontent.com/96644325/154251985-a79abcef-9b14-4787-994b-74b21f30e606.jpg)
![20220216_110112](https://user-images.githubusercontent.com/96644325/154252023-9ac5eb8f-6058-4438-a17a-b06512c71320.jpg)

**Comment by tn2009** [comment]
Strange, restart and it working:)
