### ISSUE TITLE
Pre-flight POT checks - low priority

### ISSUE THREAD

**Issue by megacct** [OpenI6X/opentx#165]
Thanks for addressing the pre-flight checks for switches. 

If Space and Time permit, please backport the pre-flight checks for POTs. This is low priority and should give way to any other demand; for Space on the device, or your Time.

**Comment by ajjjjjjjj** [comment]
No, way for elrsv2 build, it uses too much flash space and i don't want too much fragmentation between builds. So for now this is not possible.
But can wait for better times, when more flash space will be recovered.

**Comment by megacct** [comment]
Understood and expected. Can we please keep this open until such time as it's possible?

**Comment by megacct** [comment]
_"But can wait for better times, when more flash space will be recovered."_

Hi, could this change squeeze into some of the freespace now? Thanks

**Comment by ajjjjjjjj** [comment]
@megacct, unfortunately not with all languages and besides that there is still analogs debug menu that could be also reenabled.
