### ISSUE TITLE
Is there a 1ms periodic callback (like in ExdgeTx)

### ISSUE THREAD

**Issue by wimalopaan** [OpenI6X/opentx#182]
Is there a chance to call a callback every 1ms (or 2ms) ???
This is neccessary to detect the SBUS protocol pause.

This was also a problem in EdgeTx that I fixed: some RX send out SBus data with a protocol pause < 4ms. Thus must be detected, since the SBus start sequence is no unabimgously detectable.
In EdgeTx there is the `interrupt1ms()` callback in `timers_driver.cpp`. But I didn't find such thing here at the first glance.
Any hints?

**Comment by ajjjjjjjj** [comment]
I have answered in other topic can we close this one?

**Comment by wimalopaan** [comment]
Yes, thank you!
