### ISSUE TITLE
Compilation fails: language selection CZ

### ISSUE THREAD

**Issue by psicho100pro** [OpenI6X/opentx#185]
Hi again :), I tried to compile for my native language (CZ) and the compilation returns an error similar to DE #89 #100.
It's not important to me, I'm just informing. Unless I'm doing something wrong again. DE compilation works fine.

docker run --rm -it -e "BOARD_NAME=I6X" -e "CMAKE_FLAGS=PCB=I6X HELI=NO GVARS=YES LUA_COMPILER=NO MULTIMODULE=NO PPM_UNIT=PERCENT_PREC0 DEBUG=NO PCBI6X_ELRSV2=YES TRANSLATIONS=CZ" -v f:/kompilace/opentx:/opentx vitass/opentx-fw-build

[ 38%] Building CXX object radio/src/CMakeFiles/firmware.dir/telemetry/flysky_ibus.cpp.o
/tmp/opentx/radio/src/telemetry/crossfire.cpp:42:21: error: 'ZSTR_BATT_PERCENT' was not declared in this scope
make[3]: *** [radio/src/CMakeFiles/firmware.dir/build.make:336: radio/src/CMakeFiles/firmware.dir/telemetry/crossfire.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Makefile2:145: radio/src/CMakeFiles/firmware.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:157: radio/src/CMakeFiles/firmware.dir/rule] Error 2
make: *** [Makefile:131: firmware] Error 2

**Comment by ajjjjjjjj** [comment]
That's expected, i wasn't updating all the translations due to my laziness. Fixed anyway.
