### ISSUE TITLE
ppm out problem

### ISSUE THREAD

**Issue by emzeetronics** [OpenI6X/opentx#199]
there is no output ppm signal when after turned off.The signal is there again if it runs out on a factory reset, but the ppm out no signal again when it is turned off again.

I use DIY multiprotocol module. My module works normally when using the original fs-i6x firmware.

![Uploading IMG20220107112227.jpg…]()

**Comment by ajjjjjjjj** [comment]
Try this workaround and tell me if it works: https://github.com/OpenI6X/opentx/issues/155#issuecomment-1044572241

**Comment by ajjjjjjjj** [comment]
Closing because stalled.
