### ISSUE TITLE
Lua script i6x not work after ELRS 2.3.0 update

### ISSUE THREAD

**Issue by stanleykwan76** [OpenI6X/opentx#206]
Factory default BetaFPV tx module (1W) Lua script is work fine.
however, when I update to ExpressLRS firmware 2.3.0, FS-i6x Lua not work anymore.

it only show "AUX" and cannot go any function.

**Comment by stanleykwan76** [comment]
![IMG_1095](https://user-images.githubusercontent.com/101510769/158063754-f94b5d3d-c1c1-4b86-9309-34e85b8c21d5.jpg)
before update ELRS 2.3.0 (Factory shipped BetaFPV 1W JR module)

**Comment by stanleykwan76** [comment]
[https://youtu.be/GqKbjlN8QGU](url)

After upgrade tonight.
only the LUA script on i6x not work.

**Comment by ajjjjjjjj** [comment]
That's what i expected due to increased max packet size. You have to use 2.2.0 or wait for new version.

**Comment by stanleykwan76** [comment]
> 

Got is, maybe I down to 2.2.0 and see how's work.
Thanks for your great work!

**Comment by stanleykwan76** [comment]
after clam down and think what I did last night......
I remember I swith the dip swith of JR module to "update firmware" position.

and I forgot to swith it back to "Normal Operation"

Let me try tonight and switch it back and check.

**Comment by ajjjjjjjj** [comment]
Because this is already fixed on master branch i'm closing this issue.

**Comment by stanleykwan76** [comment]
After upgrade 1.4 version, LUA script work again,
Thanks
