### ISSUE TITLE
Modes don't work

### ISSUE THREAD

**Issue by Dronard** [OpenI6X/opentx#224]
I use Mode 1, it don't work

**Comment by ajjjjjjjj** [comment]
Mode 1 is swapped elevator with throttle and i see it changed properly on channels monitor.
What is your issue exactly?

**Comment by Dronard** [comment]
https://vimeo.com/696693282

**Comment by Dronard** [comment]
![Uploading Screenshot_20220406-215204_Gallery.jpg…]()

**Comment by Dronard** [comment]
![Screenshot_20220406-215204_Gallery](https://user-images.githubusercontent.com/98915844/162059474-eb06af53-c713-435a-9365-59169f601936.jpg)

**Comment by ajjjjjjjj** [comment]
It's not a mode issue but gimbal wires are swapped. Can you make a photo of your gimbal to pcb wiring?

**Comment by tn2009** [comment]
Checked mode 1 is working correctly.

**Comment by Dronard** [comment]
> It's not a mode issue but it looks more like your gimbal wires are swapped. Can you make a photo of your gimbal to pcb wiring?

The wires are short, i connect them were the should to be plug, with the flysky firmware, it work fine, I don't know why all seems to be inverted.

**Comment by Dronard** [comment]
![16492766834681019321569445310470](https://user-images.githubusercontent.com/98915844/162064518-4d906bcd-8349-4ef9-80d3-8f504c0e02bf.jpg)

**Comment by Dronard** [comment]
![16492767360398454633694747209552](https://user-images.githubusercontent.com/98915844/162064648-a0a8be8c-a50e-4cac-bbb9-1c5f95ec34f5.jpg)

**Comment by Dronard** [comment]
I simply done a strap on R53 only for the first time I upgrade to open TX firmware, then I unplug this one, because I can enter DFU mode by click on the two trim button and power on

**Comment by ajjjjjjjj** [comment]
Thanks for the pictures,  can you try to swap left and right gimbal connectors to see if that helps?

**Comment by Dronard** [comment]
![Screenshot_20220406-224914](https://user-images.githubusercontent.com/98915844/162068303-d597b246-6e63-4d81-9ad5-36770083fc73.jpg)

**Comment by Dronard** [comment]
Here is the tutorial of Rakish RC, were can I find this version ? it may be the solution

**Comment by Dronard** [comment]
> Thanks for the pictures. Can you try to swap left and right gimbal connectors(black-white with red-white one) to see if that helps?

Ok

**Comment by Dronard** [comment]
Thank you so much, i swap these wires and now everything work fine, I don't know why ancient FS firmware took this configuration right, but now it's good for me. Thank you for your replies and thank you Rakish for your precious tutorials, thanks all for this openTX firmware! I was so much upset by the poor 3 mix on FS firmware...

**Comment by ajjjjjjjj** [comment]
Thanks! will pass that to Rakesh, happy flying!

**Comment by Dronard** [comment]
Did you receive something ? I send you a video
-------- Message d'origine --------De : Janek ***@***.***> Date : 06/04/2022  18:54  (GMT+01:00) À : OpenI6X/opentx ***@***.***> Cc : Dronard ***@***.***>, Author ***@***.***> Objet : Re: [OpenI6X/opentx] Modes don't work (Issue #224) 
Mode 1 is swapped elevator with throttle and i see it changed properly on channels monitor.
What is your issue exactly?

**Comment by Dronard** [comment]
https://vimeo.com/696693282
-------- Message d'origine --------De : Janek ***@***.***> Date : 06/04/2022  18:54  (GMT+01:00) À : OpenI6X/opentx ***@***.***> Cc : Dronard ***@***.***>, Author ***@***.***> Objet : Re: [OpenI6X/opentx] Modes don't work (Issue #224) 
Mode 1 is swapped elevator with throttle and i see it changed properly on channels monitor.
What is your issue exactly?
