### ISSUE TITLE
Loading...    ?/??? ? - ExpressLRS script

### ISSUE THREAD

**Issue by Smurfgit** [OpenI6X/opentx#225]
Hi
Tools/ExpressLRS not loading.
Transmitter just says "Loading   ?/???   ?"
3 versions tried, all the same.
Any ideas or suggestions
Many thanks

**Comment by ajjjjjjjj** [comment]
Have you enabled CRSF external module protocol?

**Comment by Smurfgit** [comment]
I don't get to any menu where I can enable any protocols.
Menu 1/6 has 1 option = ExpressLRS
When I select it, the TX freezes, display says "loading  ?/???  ?

**Comment by ajjjjjjjj** [comment]
Go to model setup, scroll to External RF and set it to CRSF.

**Comment by Smurfgit** [comment]
Just completed the mod. Hasn't worked yet
Tried 1.2, 1.3 and 1.4

**Comment by Smurfgit** [comment]
You are a master.

**Comment by Smurfgit** [comment]
Working, will read through the manual. Thanx
