### ISSUE TITLE
Setting USB-Detect to auto does not work

### ISSUE THREAD

**Issue by wimalopaan** [OpenI6X/opentx#252]
Setting USB-Detect to auto, then connecting to PC does not work.

One has to select USB-Mode: auto manually.

**Comment by ajjjjjjjj** [comment]
To make "Auto" mode work you need to use `PA15` pad as USB VBUS, preferably thru resistor. FlySky i6X don't have that feature - standard cable have only GND, D+, D- lines.

**Comment by wimalopaan** [comment]
Is there a description how to modify the radio? 
So, the standard cable to the PC need to be replaced as well?

**Comment by ajjjjjjjj** [comment]
Yes and yes, see main readme.md for all possible connections and approximate location of the pads.

**Comment by wimalopaan** [comment]
Where can I get a replacement cable with this strange connector?

So. I have to use a resistor from PA15 to VBUS? Which value? 10k?

**Comment by ajjjjjjjj** [comment]
This connector does not provide USB VBUS line, it must be traced from PCB. To make it work you need new usb socket.
10k should be ok, i'm using 1k if i remember correctly.

**Comment by ajjjjjjjj** [comment]
Updated readme to make it more clear.
