### ISSUE TITLE
Save/Restore EEPROM.BIN to PC does not work

### ISSUE THREAD

**Issue by wimalopaan** [OpenI6X/opentx#253]
Connecting radio to PC and manually selecting USB-detect auto gives a connection to PC (stroage mode).

One can then copy EEPROM.BIN to PC.

If one tries to restore the EEPROM.BIN (linux: shell command), the file (seems) copied, the radio disconnects immediate, but the it reports an EEProm storage error (or sometimes EEprom full).

**Comment by ajjjjjjjj** [comment]
Thanks, i will take a look into that.

**Comment by wimalopaan** [comment]
> Thanks, i will take a look into that.

Thanks! (My tests were with 1.5.0)

**Comment by ajjjjjjjj** [comment]
I have reproduced it and found horrible bug i have made. It occurs only when copying eeprom using USB. I'm testing fix atm.

**Comment by ajjjjjjjj** [comment]
@wimalopaan , can you test it?

**Comment by wimalopaan** [comment]
> @wimalopaan , can you test it?

Of course. Did you make a PR?
