### ISSUE TITLE
Model-match based on receiver number instead of model number

### ISSUE THREAD

**Issue by prikrylm** [OpenI6X/opentx#263]
"Model-match" works, but is based on the model number (according to the order of the selected model). But in the model settings menu, there is a "Receiver Number", designed specifically to distinguish the receivers. Is it possible to use the set receiver number instead of the model number for "model-match"?
For example, due to the possibility of easier copying or moving the model in the list of models.

**Comment by ajjjjjjjj** [comment]
This is known missing feature, take a look: https://github.com/OpenI6X/opentx/issues/138

**Comment by prikrylm** [comment]
OK.
