### ISSUE TITLE
Unable to use FS-SM100 FMS Cable or Data cable for simulation

### ISSUE THREAD

**Issue by Murugesh-Hobbyist** [OpenI6X/opentx#286]
Hi,
I have flashed my FSI6X TX with OpenTX v.1.7.0
Connected the FS-SM100 RC USB Flight Simulator FMS Cable with my TX.
The device is detected but the joystick doesn't work with any of the simulation apps.

I have modified the USB mode in radio setup to joystick and USB detect to Auto.
but the simulation doesn't works. 

the same cable I'm using in fsi6 with stock firmware. it works well with all the simulation apps.
Please let me know how can I fix the issue.

![WhatsApp Image 2022-10-19 at 3 40 15 AM](https://user-images.githubusercontent.com/75427145/196565560-b3318923-ff37-4fcd-a1f6-f090b0791ff0.jpeg)

**Comment by ajjjjjjjj** [comment]
i6X is a USB device therefore do not need FS-SM100, but straight connection cable:
https://pl.aliexpress.com/item/32969339325.html

**Comment by Murugesh-Hobbyist** [comment]
The thing is, I don't have the direct cable provided in the i6x package.
so I wish to use the  FS-SM100
Please let me know how can I use it.

**Comment by ajjjjjjjj** [comment]
Make your own cable, i.e.:
https://www.youtube.com/watch?v=8p419msLeyM

**Comment by Murugesh-Hobbyist** [comment]
I made the cable. Now I can communicate with TX for firmware flashing.
But for simulation, the driver not seems to be working.
![WhatsApp Image 2022-10-20 at 12 25 00 AM](https://user-images.githubusercontent.com/75427145/196779691-759f220a-19ca-4213-9f6a-4d1a287b9bad.jpeg)
![Screenshot - 20-10-2022 , 12_20_30 AM](https://user-images.githubusercontent.com/75427145/196778746-fa6d54f8-c830-4181-b662-d85ebf7f5a06.png)
![Screenshot - 20-10-2022 , 12_21_26 AM](https://user-images.githubusercontent.com/75427145/196778876-2c162081-69f5-4c15-a5bd-6f5ecb4aac04.png)


I also tried the following the below video, still it didn't worked out.
[https://www.youtube.com/watch?v=mRFiRYlpvoM&t=237s](url)

Please help me how can i use this cable for simulation by fixing the driver issue.

**Comment by ajjjjjjjj** [comment]
There are known issues with USB Joystick, look thru other USB issues to get familiar with it. Also see: https://github.com/OpenI6X/opentx#usb-connection

**Comment by Murugesh-Hobbyist** [comment]
I exactly did the same.
FlySky FS-i6X don't have a USB VBUS making it impossible to detect USB connection. Without the modification you have to go to General settings and set USB Detect to "Once" every time you're connecting USB.

The device is detected as joystick but the driver is not apt able. and I could see a square box on top left after driver update.
![WhatsApp Image 2022-10-20 at 12 33 58 AM](https://user-images.githubusercontent.com/75427145/196781572-660f1c27-19ba-4668-bfef-7b387be5f8cb.jpeg)

**Comment by Murugesh-Hobbyist** [comment]
Hi Team,

I have tested the simulation by flashing the backed up stock firmware.
I can use both the data cable and simulator cable for simulation in stock firmware but not in open Tx.

When I use the stock firmware with data cable,
![Screenshot - 22-10-2022 , 12_21_32 AM](https://user-images.githubusercontent.com/75427145/197268787-4a5b7c1e-90c5-4c8a-9bcc-41e463c1eb57.png)


When I use the stock firmware with simulator cable,
![Screenshot - 22-10-2022 , 12_25_00 AM](https://user-images.githubusercontent.com/75427145/197269257-65da336b-c0e6-4ff9-b81e-6c808cb3e92a.png)

But in Open TX, it doesn't working even if I change the radio setup -> Usbmode and usb detect.

**Comment by Murugesh-Hobbyist** [comment]
Anyways found a solution to use the IBUS protocol in receiver, to use the Open TX firmware communication for simulation wirelessly. Thanks for the help. I'm closing the issue.
