### ISSUE TITLE
align hardware name to left?

### ISSUE THREAD

**Issue by psicho100pro** [OpenI6X/opentx#299]
when i create a name in hardware for anything, then in the inputs that name interferes with the curve rendering
![20221112_203217](https://user-images.githubusercontent.com/97060304/201492647-c43f75a4-5be2-430c-84be-1fe6a2a7a80a.jpg)

**Comment by ajjjjjjjj** [comment]
Can you share your configuration details - where is "arm" defined to be available as a source?

**Comment by psicho100pro** [comment]
It doesn't matter what resource I use, and only how I name it, if a name is assigned, its name always hits the graph
, I now have two transmitters, on one the second version with dicord and the second compilation v1.8.0 without elrs and they do the same thing.
If only the native name is , everything is fine.
![bandicam 2022-11-13 12-18-32-872](https://user-images.githubusercontent.com/97060304/201519005-7fe15abf-1157-4a02-9d93-d769fb71f3e0.jpg)
![bandicam 2022-11-13 12-18-52-208](https://user-images.githubusercontent.com/97060304/201519007-d4de9997-e8c1-4d8d-a1de-4a40e86e8e96.jpg)

**Comment by ajjjjjjjj** [comment]
It does matter. If you cannot answer my question i cannot help you.

**Comment by psicho100pro** [comment]
In that case I worded it wrong,,,
All the switches do it, if i assign a name to it it moves like to the right and hits the graph.
Pots do the same,,

**Comment by ajjjjjjjj** [comment]
Ok, so it's a switch name, because i.e. output name works differently.
