### ISSUE TITLE
Own compilation

### ISSUE THREAD

**Issue by stryjekryjek** [OpenI6X/opentx#347]
I used my 1.7.0 build before, the only change I made was I added PPM_UNIT=US to docker.  csf worked without a problem.  Today I downloaded a new version and wanted to compile the same, but after uploading crsf it does not work, I thought I would use the default line 
`docker run --rm -it -e "BOARD_NAME=I6X" -e "CMAKE_FLAGS=PCB=I6X HELI=NO GVARS=YES LUA_COMPILER=NO  MULTIMODULE=NO PCBI6X_ELRSV3=NO DEBUG=NO" -v ${PWD}:/opentx ajjjjjjjj/opentx-docker-i6x `
but no effect. Crsf not work. However, if I upload the bin file from github everything works 1.9.0.  Unfortunately when it compiles it doesn't work.  Do I need to use some additional attribute? 
Is this a bug in the new version?  because in 1.7.0 it works.

`/flysky_qlrs/opentx# docker run --rm -it -e "BOARD_NAME=I6X" -e "CMAKE_FLAGS=PCB=I6X HELI=NO GVARS=YES LUA_COMPILER=NO PPM_UNIT=US TRANSLATIONS=PL MULTIMODULE=NO PCBI6X_ELRSV3=NO DEBUG=NO" -v ${PWD}:/opentx ajjjjjjjj/opentx-docker-i6x

The script to build opentx firmware with docker image  ajjjjjjjj/opentx-docker-i6x based on vitass/opentx-fw--build

Board name: I6X
Additional CMAKE Flags: PCB=I6X HELI=NO GVARS=YES LUA_COMPILER=NO PPM_UNIT=US TRANSLATIONS=PL MULTIMODULE=NO PCBI6X_ELRSV3=NO DEBUG=NO

WARNING: Unknown board (I6X) specified
Firmware will be built with generic defaults and any specified CMAKE flags.

Adding additional flag: PCB=I6X
Overriding default flag: HELI=YES => HELI=NO
Override for default flag matches default value: GVARS=YES
Overriding default flag: LUA_COMPILER=YES => LUA_COMPILER=NO
Override for default flag matches default value: PPM_UNIT=US
Adding additional flag: TRANSLATIONS=PL
Overriding default flag: MULTIMODULE=YES => MULTIMODULE=NO
Adding additional flag: PCBI6X_ELRSV3=NO
Adding additional flag: DEBUG=NO

Copying source from /opentx to /tmp/opentx ...

cmake -DGUI=YES -DGVARS=YES -DHELI=NO -DLUA=NO -DLUA_COMPILER=NO -DMULTIMODULE=NO -DPPM_CENTER_ADJUSTABLE=YES -DPPM_UNIT=US -DRAS=YES -DDISABLE_COMPANION=YES -DCMAKE_BUILD_TYPE=Release -DPCB=I6X -DTRANSLATIONS=PL -DPCBI6X_ELRSV3=NO -DDEBUG=NO /tmp/opentx

-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:14 (cmake_policy):
  The OLD behavior for policy CMP0023 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found Git: /usr/bin/git (found version "2.20.1")
-- Git repository not found, revision number not available.
-- OpenTX 1.9.0 @0
-- Found PythonInterp: /usr/local/bin/python (found version "3.8.12")
-- Python found, version: 3.8.12
TARGET simu/libsimulator: cpp compiler /usr/bin/c++ v8
CMake Warning at radio/src/tests/CMakeLists.txt:45 (message):
  WARNING: gtests target will not be available (check that GTEST_INCDIR,
  GTEST_SRCDIR, and Qt5Widgets are configured).

-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
TARGET firmware: cpp compiler arm-none-eabi-g++ v12.2.1
-- Configuring done
-- Generating done
-- Build files have been written to: /build
Scanning dependencies of target 9x_xbm_1bit
Scanning dependencies of target 9x_fonts_1bit
[  1%] Generating sticks.lbm
[  1%] Generating font_03x05.lbm
[  3%] Generating font_04x06.lbm
[  3%] Generating font_04x06_extra.lbm
[  3%] Built target 9x_xbm_1bit
Scanning dependencies of target firmware_translations
[  3%] Generating cz.h
[  3%] Generating font_05x07.lbm
[  3%] Generating de.h
[  4%] Generating font_05x07_B_compressed.lbm
[  4%] Generating en.h
[  4%] Generating font_05x07_extra.lbm
[  6%] Generating es.h
[  6%] Generating font_08x10.lbm
[  6%] Generating fi.h
[  6%] Generating fr.h
[  6%] Generating font_10x14.lbm
[  7%] Generating it.h
[  7%] Generating nl.h
[  9%] Generating font_10x14_compressed.lbm
[  9%] Generating pl.h
[  9%] Generating font_10x14_extra.lbm
[  9%] Generating pt.h
[  9%] Generating font_22x38_num.lbm
[ 11%] Generating se.h
[ 11%] Built target firmware_translations
[ 12%] Generating font_cz_04x06.lbm
[ 12%] Generating font_cz_05x07.lbm
[ 12%] Generating font_cz_08x10.lbm
[ 12%] Generating font_cz_10x14.lbm
[ 14%] Generating font_de_04x06.lbm
[ 14%] Generating font_de_05x07.lbm
[ 14%] Generating font_de_08x10.lbm
[ 15%] Generating font_de_10x14.lbm
[ 15%] Generating font_es_04x06.lbm
[ 15%] Generating font_es_05x07.lbm
[ 15%] Generating font_es_08x10.lbm
[ 17%] Generating font_es_10x14.lbm
[ 17%] Generating font_fi_04x06.lbm
[ 17%] Generating font_fi_05x07.lbm
[ 17%] Generating font_fi_08x10.lbm
[ 19%] Generating font_fi_10x14.lbm
[ 19%] Generating font_fr_04x06.lbm
[ 19%] Generating font_fr_05x07.lbm
[ 20%] Generating font_fr_08x10.lbm
[ 20%] Generating font_fr_10x14.lbm
[ 20%] Generating font_it_04x06.lbm
[ 20%] Generating font_it_05x07.lbm
[ 22%] Generating font_it_08x10.lbm
[ 22%] Generating font_it_10x14.lbm
[ 22%] Generating font_pl_04x06.lbm
[ 23%] Generating font_pl_05x07.lbm
[ 23%] Generating font_pl_08x10.lbm
[ 23%] Generating font_pl_10x14.lbm
[ 23%] Generating font_pt_04x06.lbm
[ 25%] Generating font_pt_05x07.lbm
[ 25%] Generating font_pt_08x10.lbm
[ 25%] Generating font_pt_10x14.lbm
[ 26%] Generating font_se_04x06.lbm
[ 26%] Generating font_se_05x07.lbm
[ 26%] Generating font_se_08x10.lbm
[ 26%] Generating font_se_10x14.lbm
[ 26%] Built target 9x_fonts_1bit
Scanning dependencies of target 9x_bitmaps
[ 26%] Generating about.lbm
[ 26%] Generating asterisk.lbm
[ 26%] Generating sleep.lbm
[ 28%] Generating splash.lbm
[ 28%] Generating splash_i6x_neg_trim.lbm
[ 28%] Generating splash_i6x_trim.lbm
[ 28%] Built target 9x_bitmaps
Scanning dependencies of target firmware
[ 28%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/keys_driver.cpp.o
[ 28%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/telemetry_driver.cpp.o
[ 30%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/pulses_driver.cpp.o
[ 30%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/aux_serial_driver.cpp.o
[ 30%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/cpu_id.cpp.o
[ 30%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/rtc_driver.cpp.o
[ 31%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/mixer_scheduler_driver.cpp.o
[ 31%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/crc_driver.cpp.o
[ 31%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/i2c_driver.cpp.o
[ 31%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/adc_driver.cpp.o
[ 33%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/extmodule_driver.cpp.o
[ 33%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/backlight_driver.cpp.o
[ 33%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/buzzer_driver.cpp.o
[ 34%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/board.cpp.o
[ 34%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/timers_driver.cpp.o
[ 34%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/trainer_driver.cpp.o
[ 34%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/intmodule_pulses_driver.cpp.o
[ 36%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/AFHDS2A_a7105.cpp.o
[ 36%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/A7105_SPI.cpp.o
[ 36%] Building CXX object radio/src/CMakeFiles/firmware.dir/buzzer.cpp.o
[ 38%] Building CXX object radio/src/CMakeFiles/firmware.dir/telemetry/crossfire.cpp.o
[ 38%] Building CXX object radio/src/CMakeFiles/firmware.dir/telemetry/flysky_ibus.cpp.o
[ 38%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_cz.cpp.o
[ 38%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_de.cpp.o
[ 39%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_en.cpp.o
[ 39%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_es.cpp.o
[ 39%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_fr.cpp.o
[ 41%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_it.cpp.o
[ 41%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_pt.cpp.o
[ 41%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_sk.cpp.o
[ 41%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_se.cpp.o
[ 42%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_pl.cpp.o
[ 42%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_hu.cpp.o
[ 42%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_nl.cpp.o
[ 44%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations/tts_ru.cpp.o
[ 44%] Building CXX object radio/src/CMakeFiles/firmware.dir/main.cpp.o
[ 44%] Building CXX object radio/src/CMakeFiles/firmware.dir/tasks.cpp.o
[ 44%] Building CXX object radio/src/CMakeFiles/firmware.dir/telemetry/telemetry.cpp.o
[ 46%] Building CXX object radio/src/CMakeFiles/firmware.dir/telemetry/telemetry_holders.cpp.o
[ 46%] Building CXX object radio/src/CMakeFiles/firmware.dir/telemetry/telemetry_sensors.cpp.o
[ 46%] Building CXX object radio/src/CMakeFiles/firmware.dir/crc.cpp.o
[ 46%] Building CXX object radio/src/CMakeFiles/firmware.dir/vario.cpp.o
[ 47%] Building CXX object radio/src/CMakeFiles/firmware.dir/debug.cpp.o
[ 47%] Building CXX object radio/src/CMakeFiles/firmware.dir/storage/storage_common.cpp.o
[ 47%] Building CXX object radio/src/CMakeFiles/firmware.dir/storage/eeprom_common.cpp.o
[ 49%] Building CXX object radio/src/CMakeFiles/firmware.dir/storage/eeprom_rlc.cpp.o
[ 49%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/widgets.cpp.o
[ 49%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/navigation/navigation_9x.cpp.o
[ 49%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/navigation/common.cpp.o
[ 50%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/arm/widgets.cpp.o
[ 50%] Building CXX object radio/src/CMakeFiles/firmware.dir/curves.cpp.o
[ 52%] Building CXX object radio/src/CMakeFiles/firmware.dir/gvars.cpp.o
[ 52%] Building CXX object radio/src/CMakeFiles/firmware.dir/rtc.cpp.o
[ 52%] Building CXX object radio/src/CMakeFiles/firmware.dir/opentx.cpp.o
[ 52%] Building CXX object radio/src/CMakeFiles/firmware.dir/functions.cpp.o
[ 52%] Building CXX object radio/src/CMakeFiles/firmware.dir/strhelpers.cpp.o
[ 53%] Building CXX object radio/src/CMakeFiles/firmware.dir/switches.cpp.o
[ 53%] Building CXX object radio/src/CMakeFiles/firmware.dir/mixer.cpp.o
[ 53%] Building CXX object radio/src/CMakeFiles/firmware.dir/mixer_scheduler.cpp.o
[ 55%] Building CXX object radio/src/CMakeFiles/firmware.dir/stamp.cpp.o
[ 55%] Building CXX object radio/src/CMakeFiles/firmware.dir/timers.cpp.o
[ 55%] Building CXX object radio/src/CMakeFiles/firmware.dir/trainer.cpp.o
[ 55%] Building CXX object radio/src/CMakeFiles/firmware.dir/keys.cpp.o
[ 57%] Building CXX object radio/src/CMakeFiles/firmware.dir/maths.cpp.o
[ 57%] Building CXX object radio/src/CMakeFiles/firmware.dir/translations.cpp.o
[ 57%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/gui_common.cpp.o
[ 57%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_input_edit.cpp.o
[ 58%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_mix_edit.cpp.o
[ 58%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_display.cpp.o
[ 58%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/radio_diagkeys.cpp.o
[ 60%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/radio_diaganas.cpp.o
[ 60%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/radio_hardware.cpp.o
[ 60%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/view_channels.cpp.o
/tmp/opentx/radio/src/gui/128x64/radio_hardware.cpp: In function 'void menuRadioHardware(event_t)':
/tmp/opentx/radio/src/gui/128x64/radio_hardware.cpp:265:99: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  265 |         lcdDrawTextAtIndex(INDENT_WIDTH, y, STR_VSRCRAW, NUM_STICKS+idx+1, menuHorizontalPosition < 0 ? attr : 0);
      |                                                                            ~~~~~~~~~~~~~~~~~~~~~~~^~~
/tmp/opentx/radio/src/gui/128x64/radio_hardware.cpp:294:121: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  294 |         lcdDrawTextAtIndex(INDENT_WIDTH, y, STR_VSRCRAW, MIXSRC_FIRST_SWITCH-MIXSRC_Rud+index+1, menuHorizontalPosition < 0 ? attr : 0);
      |                                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~^~~
[ 60%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/view_telemetry.cpp.o
[ 61%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/view_about.cpp.o
[ 61%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_gvars.cpp.o
[ 61%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/lcd.cpp.o
[ 63%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/splash.cpp.o
[ 63%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/fonts.cpp.o
[ 63%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/popups.cpp.o
[ 63%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/widgets.cpp.o
[ 65%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/menus.cpp.o
[ 65%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/menu_model.cpp.o
[ 65%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_select.cpp.o
[ 66%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_setup.cpp.o
[ 66%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_outputs.cpp.o
/tmp/opentx/radio/src/gui/128x64/model_setup.cpp: In function 'void menuModelSetup(event_t)':
/tmp/opentx/radio/src/gui/128x64/model_setup.cpp:619:48: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  619 |           if (attr && ((menuHorizontalPosition < 0) || menuHorizontalPosition >= NUM_SWITCHES)) {
      |                         ~~~~~~~~~~~~~~~~~~~~~~~^~~
[ 66%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_logical_switches.cpp.o
[ 66%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_special_functions.cpp.o
[ 68%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_telemetry.cpp.o
[ 68%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/menu_radio.cpp.o
[ 68%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/radio_setup.cpp.o
[ 69%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/radio_version.cpp.o
[ 69%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/radio_calibration.cpp.o
[ 69%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/view_main.cpp.o
[ 69%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/view_statistics.cpp.o
[ 71%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/widgets.cpp.o
[ 71%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/popups.cpp.o
[ 71%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/radio_tools.cpp.o
[ 71%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/model_inputs.cpp.o
[ 73%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/model_mixes.cpp.o
[ 73%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/view_text.cpp.o
[ 73%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/radio_trainer.cpp.o
[ 74%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/common/stdlcd/model_curves.cpp.o
[ 74%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_curve_edit.cpp.o
[ 74%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/128x64/model_flightmodes.cpp.o
[ 74%] Building CXX object radio/src/CMakeFiles/firmware.dir/gui/gui_common_arm.cpp.o
[ 76%] Building CXX object radio/src/CMakeFiles/firmware.dir/sbus.cpp.o
[ 76%] Building CXX object radio/src/CMakeFiles/firmware.dir/pulses/crossfire.cpp.o
[ 76%] Building CXX object radio/src/CMakeFiles/firmware.dir/pulses/pulses_arm.cpp.o
[ 77%] Building CXX object radio/src/CMakeFiles/firmware.dir/pulses/ppm_arm.cpp.o
[ 77%] Building CXX object radio/src/CMakeFiles/firmware.dir/serial.cpp.o
[ 77%] Building C object radio/src/CMakeFiles/firmware.dir/syscalls.c.o
[ 77%] Building ASM object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/CMSIS/Device/ST/STM32F0xx/Source/Templates/gcc_ride7/startup_stm32f072.s.o
[ 79%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_crs.c.o
[ 79%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_misc.c.o
[ 79%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_gpio.c.o
[ 80%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_dbgmcu.c.o
[ 80%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_rcc.c.o
[ 80%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_spi.c.o
[ 80%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_i2c.c.o
[ 82%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_dma.c.o
[ 82%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_rtc.c.o
[ 82%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_pwr.c.o
[ 84%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_usart.c.o
[ 84%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_adc.c.o
[ 84%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_crc.c.o
[ 84%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Driver/src/usb_core.c.o
[ 85%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Driver/src/usb_dcd.c.o
[ 85%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Driver/src/usb_dcd_int.c.o
[ 85%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Library/Core/src/usbd_core.c.o
[ 85%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Library/Core/src/usbd_ioreq.c.o
[ 87%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Library/Core/src/usbd_req.c.o
[ 87%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Library/Class/msc/src/usbd_msc_data.c.o
[ 87%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Library/Class/msc/src/usbd_msc_scsi.c.o
[ 88%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Library/Class/msc/src/usbd_msc_bot.c.o
[ 88%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/STM32F0x2_USB-FS-Device_Lib_V1.0.0/Libraries/STM32_USB_Device_Library/Class/msc/src/usbd_msc_core.c.o
[ 88%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/core.c.o
[ 88%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/hook.c.o
[ 90%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/task.c.o
[ 90%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/event.c.o
[ 90%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/time.c.o
[ 92%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/timer.c.o
[ 92%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/flag.c.o
[ 92%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/mutex.c.o
[ 92%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/kernel/serviceReq.c.o
[ 93%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/portable/GCC/port.c.o
[ 93%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/CoOS/portable/arch.c.o
[ 95%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/pwr_driver.cpp.o
[ 95%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/flysky/lcd_driver.cpp.o
[ 95%] Building C object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/f0/system_stm32f0xx.c.o
[ 95%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/delays.cpp.o
[ 95%] Building C object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/usb_bsp.c.o
[ 95%] Building C object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/usbd_desc.c.o
[ 96%] Building C object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/usbd_pwr.c.o
[ 96%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/usbd_usr.cpp.o
[ 96%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/usb_driver.cpp.o
[ 98%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/flash_driver.cpp.o
[ 98%] Building CXX object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/usbd_storage_msd.cpp.o
[ 98%] Building C object radio/src/CMakeFiles/firmware.dir/targets/common/arm/stm32/usbd_hid_joystick.c.o
[100%] Linking CXX executable ../../firmware.elf
lto-wrapper: warning: using serial compilation of 4 LTRANS jobs
lto-wrapper: note: see the '-flto' option documentation for more information
In function '__set_MSP',
    inlined from 'SystemBootloaderJump' at /tmp/opentx/radio/src/targets/flysky/board.cpp:148:14,
    inlined from 'boardInit' at /tmp/opentx/radio/src/targets/flysky/board.cpp:210:25,
    inlined from 'main' at /tmp/opentx/radio/src/opentx.cpp:1899:12:
/tmp/opentx/radio/src/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/CMSIS/Device/ST/STM32F0xx/Include/core_cmFunc.h:468:3: warning: listing the stack pointer register 'sp' in a clobber list is deprecated [-Wdeprecated]
  468 |   __ASM volatile ("MSR msp, %0\n" : : "r" (topOfMainStack) : "sp");
      |   ^
/tmp/opentx/radio/src/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/CMSIS/Device/ST/STM32F0xx/Include/core_cmFunc.h:468:3: note: the value of the stack pointer after an 'asm' statement must be the same as it was before the statement
/tmp/opentx/radio/src/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_usart.c: In function 'USART_Init.constprop':
/tmp/opentx/radio/src/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_usart.c:306:14: warning: 'RCC_ClocksStatus.USART3CLK_Frequency' may be used uninitialized [-Wmaybe-uninitialized]
  306 |     apbclock = RCC_ClocksStatus.USART3CLK_Frequency;
      |              ^
/tmp/opentx/radio/src/thirdparty/STM32F0xx_StdPeriph_Lib_V1.5.0/Libraries/STM32F0xx_StdPeriph_Driver/src/stm32f0xx_usart.c:239:21: note: 'RCC_ClocksStatus.USART3CLK_Frequency' was declared here
  239 |   RCC_ClocksTypeDef RCC_ClocksStatus;
      |                     ^
Flash used: 125696 / 131072 (95%), left: 5376
RAM used: 16008 / 16384 (97%), left: 376
[100%] Built target firmware

Build completed in 58.9 seconds.

Firmware file: /opentx/opentx-i6x-1.9.0-pl.bin

WARNING: Unable to validate firmware image size
Firmware size: 122.75KB
`

**Comment by ajjjjjjjj** [comment]
I assume you are using TBS module, can you show how ExpressLRS tool is working with it?

Try: BOARD_NAME=i6x , lowercase letters.
