### ISSUE TITLE
ibus16 RX  CH15/16

### ISSUE THREAD

**Issue by didinski** [OpenI6X/opentx#355]
Hello 

has anybody tested the channels 15 and 16 on a recent RX `? I do have a new ia10b and only get 14 channels. RSSI works fine.

In this thread (https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/390) wimalopaan said he can receive Ch15/16 on a ia6b.

Ive tested with vjoyserial feeder and some arduino code. Always 14 Channels. Ibus16 is set of course

**Comment by ajjjjjjjj** [comment]
I have ia6b, not recent one and was working fine by the time i tested it.

**Comment by wimalopaan** [comment]
I definitly works with 16 channels.
I think this could be closed then.
