### ISSUE TITLE
Cant get the joystick mode to work

### ISSUE THREAD

**Issue by bfgelectronics** [OpenI6X/opentx#360]
I updated from the stock firmware to the OpenTX1.9 and now the joystick function doesnt work, in windows when i connect it it shows up like this:
![image](https://github.com/OpenI6X/opentx/assets/44001993/0fedf954-9b8a-43b2-8766-84ba7bc3493c) 
(the usb storage mode works)
and in linux it looks like this :
![image](https://github.com/OpenI6X/opentx/assets/44001993/e465356f-f166-4933-8c65-5e20800fe858)
 But still isnt recognised as a joystick.
 
 What should i try ( i have to mention that the only mod i have is the battery mod).

**Comment by florin-baciu** [comment]
Watched over other issues and found out this is a duplicate, please close.
