### ISSUE TITLE
Issues Trying to Get the I6X Detected by the SMT32 Programmer

### ISSUE THREAD

**Issue by Mel4221** [OpenI6X/opentx#365]
Hi Im currently trying to flash the OpenTX firmware to my I6X But sadly it seems that they change the processor and it requires a different programer  since i wire up everything completly as  i was supposed to exacly as show here: https://github.com/OpenI6X/opentx/raw/master/doc/flysky/dfu_jump_r53.jpg
but it did not work so i gess that based on the chip model of the SMT32 is possible that they did something different, but im not sure , either way i found some information about the manufacture which is:  https://global.geehy.com/support/apm32/?id=202
if you guys have any suggestion please let me know i will be willing to provide any picture or information

**Comment by ajjjjjjjj** [comment]
There are alternatives for APM32 MCUs described in wiki:
https://github.com/OpenI6X/opentx/wiki#alternatively-flash-using-stm32-cubeprogrammergeehy-dfuprogrammerqmk-toolbox

**Comment by Mel4221** [comment]
> There are alternatives for APM32 MCUs described in wiki: https://github.com/OpenI6X/opentx/wiki#alternatively-flash-using-stm32-cubeprogrammergeehy-dfuprogrammerqmk-toolbox
i will try the other ones , due to the STM32 CubeProgrammer did not work for me for some reason does not recognized it at all
thanks for answering..

**Comment by Mel4221** [comment]
First Thanks a lot for answering one more time @ajjjjjjjj here is some information about my current status  on this issue.

I have fallow the process described on the wiki and also some videos on youtube on the steps of how to install OpenI6X on my radio sadly my radio has de APM32 MCU which lacks on some videos on youtube on how to properly fallow the step by step flashing process , but here are some pictures of my process: 

step1: i first bridge the pad R53 as explained in the wiki
setep2:  solder the rest of the wires acording to the picture in the wiki here is how it looks:

>My soldering skills don't look good at all :-)
![Wiring](https://github.com/OpenI6X/opentx/assets/87794877/b46f4f30-8539-49fd-b17c-0c65c61b9892)

step3: now i got on the computer and before i did anything i connected everything to the ST-Link device with each wire accordingly  then  i turned on the Radio which as expected did not  turn on the lights  then i connected the connector to the computer but which made a sound but here is my original issue any of the Programmers are either not detecting the  device here is some more pictures : 
>QMK_ToolBox
<img width="960" alt="QMK_ToolBox" src="https://github.com/OpenI6X/opentx/assets/87794877/69e49996-611d-4dfe-9618-53e73e46a9e6">

>APM32_Programer
<img width="630" alt="APM32_Programer" src="https://github.com/OpenI6X/opentx/assets/87794877/004756d5-0b0a-4c27-af64-383a087a375f">

>SMT32_CubeProgrammer
<img width="960" alt="SMT32_CubeProgrammer_with_StlinkMode" src="https://github.com/OpenI6X/opentx/assets/87794877/7ecf2066-ff19-46cb-9017-167a60fc92e9">
>SMT32_CubeProgrammer
<img width="960" alt="SMT32_CubeProgrammer_with_usbmode" src="https://github.com/OpenI6X/opentx/assets/87794877/33d0bbc6-9ba1-4e17-94d2-94e42fe7d828">

@ajjjjjjjj  if you have any suggestion or ideas please let me know , and again thanks a lot for taking a second to answer.

**Comment by Mel4221** [comment]
I have had some minimal progress 
but still nothing yet 
<img width="597" alt="image" src="https://github.com/OpenI6X/opentx/assets/87794877/d853a2ca-f8ca-4bcd-8b56-babc7ac649d9">
i even found a video on youtube with a different approuch on how to flash it(https://www.youtube.com/watch?v=ujlnielHad4 ) , but still same problem i am not getting it detected by the drivers manager 
<img width="278" alt="image" src="https://github.com/OpenI6X/opentx/assets/87794877/3feafaa5-b022-4864-8425-4dbe1ec70326">

**Comment by Ultraexpert** [comment]
Uninstall the driver restart pc,check new batteries,put into dfu mode , plug in i6x into pc, open qmktoolbox
Flash. Search keenas on rcgroups I have a guide somewhere on there.

**Comment by Ultraexpert** [comment]
I plan to share a video demonstrating my process with the APM32 once I find the time to upgrade to the recently released iNav version. Anticipating to have it ready by next week!

**Comment by Ultraexpert** [comment]
I found the old post for you https://www.rcgroups.com/forums/showthread.php?3916435-FlySky-I6X-port-of-OpenTX/page16#post48731989

**Comment by japanel** [comment]
@Mel4221 Hi, why you do t use original cable you got with your I6X? I flashed with DFUprogrammer on first try withou any problem. I had APM32 too. I soldered R53 pads only then use original cable, without issue.

**Comment by Mel4221** [comment]
> @Mel4221 Hi, why you dont use original cable you got with your I6X? I flashed with DFUprogrammer on first try without any problem. I had APM32 too. I soldered R53 pads only then use original cable, without issue.

That would be aswome i was currently using the ST-Link v2 for that and i also try using the DFUProgrammer for that but not much luck on that either because is not detecting the DFU Mode status for some reason even through the pads are sordered correctly. 

But if you have a link to the installer for the DFUProgrammer that you used please shared it that i would be willing to give it a try , are  some pictures about my actual results: 
>for some reason i can not see why is not getting detected and the pad R53 is the one that is Briged so i don't know where to start if i am not getting  any signal that the device is getting detected as being in DFUMode for some reason
<img width="960" alt="image" src="https://github.com/OpenI6X/opentx/assets/87794877/aa1ac534-7731-456d-be08-2c5c9f9ad6e6">

Thanks so much for answering @japanel

**Comment by Mel4221** [comment]
> I plan to share a video demonstrating my process with the APM32 once I find the time to upgrade to the recently released iNav version. Anticipating to have it ready by next week!

@Ultraexpert Thanks a lot for all the support i am currently reading all the information that you provided ,  so i will keep you all posted about my current state and again thanks a lot for all your help @Ultraexpert

**Comment by Mel4221** [comment]
I Mean i don't know how but  for some reason now when i tried again it was detected by the DFUProgramer by using the original cabel directly instead of the ST-Link
One more time thanks a lot @japanel 
<img width="960" alt="image" src="https://github.com/OpenI6X/opentx/assets/87794877/9d4ab345-866c-4891-bd60-1cbac5117c51">

**Comment by japanel** [comment]
> I Mean i don't know how but for some reason now when i tried again it was detected by the DFUProgramer by using the original cabel directly instead of the ST-Link One more time thanks a lot @japanel <img alt="image" width="960" src="https://user-images.githubusercontent.com/87794877/258581383-9d4ab345-866c-4891-bd60-1cbac5117c51.png">

@Mel4221 great, same version, downloaded from https://global.geehy.com/support/apm32/?id=383
I hope you are sucessfull now.

**Comment by Mel4221** [comment]
I Would like to start first by saying thanks to all of you that gave me so much assitence through this process of flashing my radio , thanks a lot for being patient and also for the time inbested to help @ajjjjjjjj  @Ultraexpert  @japanel @marianomd 

So  yeah finally i was able to do it flash it , and im going to list down the issues that i strugle with the most 

1.  Wrong wiring to the ST-LINK which was my mistake entirely 
2.  Not Needed Drivers since i only needed to download the QMX Toolbox which had all the drivers that i  needed 
3.  The DFU Programer here : works on regards that it does detect the device but it did not allow me to flash it for some reason ("The flashing button did never appear for some reason")
4. I Had some random issues with the QMX Toolbox  because it was always able to detect the APM32 but it was giving me an error at flashing time later on i notice that one i lunch it from the terminal it change one Setting  to this value <img width="115" alt="image" src="https://github.com/OpenI6X/opentx/assets/87794877/96689c83-ec35-4444-81a1-a259ad4e0ca4">  
which i trully have no idea what is for but it looks to be the right setting for my MCU 



**One More  Time Thanks a lot for all your help : @ajjjjjjjj  @Ultraexpert  @japanel @marianomd **

> Here is 
![20230805_084416](https://github.com/OpenI6X/opentx/assets/87794877/44ba9758-5fc0-4fb2-b4d5-37472f127331)

>I Added the wire for the Back light 
![20230805_084024](https://github.com/OpenI6X/opentx/assets/87794877/3708da71-4de5-447c-8bbd-864b997e752b)
