### ISSUE TITLE
telemetry mirror

### ISSUE THREAD

**Issue by marco5959** [OpenI6X/opentx#369]
I haven't installed a new system yet, but I have a question, maybe a stupid one. What does an exemplary projection of a telemetric mirror on the PA9 output look like. ??

**Comment by ajjjjjjjj** [comment]
It depends on protocol used - AFHDS2A or CRSF. 
AFHDS2A streams data in Multiprotocol Module standard, 
CRSF streams raw CRSF telemetry.

**Comment by marco5959** [comment]
Thank You Janek
