### ISSUE TITLE
Driver error

### ISSUE THREAD

**Issue by SiulroKe** [OpenI6X/opentx#372]
Driver error
When I connected the remote control to the computer, I encountered the problem that the driver could not be installed. Do I need to download a separate driver? Could you provide a download address?
![9e49756f-5bbb-44bf-b48b-6ea989e3d748](https://github.com/OpenI6X/opentx/assets/101232282/90a54ee4-d8cb-4ff2-9fcb-c72ec4f2eaef)

**Comment by AzwadAbid** [comment]
Please ensure that you jumped the two pins of R53 first. 
Also, install the [STM32 Cube Software](https://www.st.com/en/development-tools/stm32cubeprog.html). While it is installing, the drivers are installed as well.

For video instuction, you can follow "[Rakish Rc](https://www.youtube.com/watch?v=5jW7gGt15EI)" on Youtube. For me, his instructions were useful.
