### ISSUE TITLE
editing GVARS - system reboot

### ISSUE THREAD

**Issue by didinski** [OpenI6X/opentx#387]
Hello

when I set GVARS in Flight Modes the system sometimes makes a reboot? and an exclamation mark appears in the upper right corner.
I've tried factory reset but its still present. I'm not sure what causes the problem. But its always when I edit GVARS > #6.
GVARS 1-5 seem to work as expected.

using 1.11.1

**Comment by ajjjjjjjj** [comment]
Can you add detailed steps and/or video of issue reproduction?

**Comment by didinski** [comment]
just saw your answer..

i cruicial point was to edit many gvars (min. 1-6) and then edit >5. as far as i remember.

i will have a look and come back

**Comment by ajjjjjjjj** [comment]
Can you attach yout eeprom configuration here?

**Comment by didinski** [comment]
its always when i edit the **Name** of **GVAR6**. checked it. 
tested with 1.11.1, 1.11.0 and 1.10.0


[EEPROM.zip](https://github.com/user-attachments/files/16036589/EEPROM.zip)

**Comment by ajjjjjjjj** [comment]
I have tested it on your config, seems to be fixed. Can you try by yourself on https://github.com/OpenI6X/opentx/pull/411 ?
