### ISSUE TITLE
Servo center adjustment - nothing happens

### ISSUE THREAD

**Issue by didinski** [OpenI6X/opentx#392]
Hello

in the OTX 2.2 Manual you can read:

"Center adjustment. This is similar to subtrim, with the difference that an adjustment done here will shift the entire servo throw (including limits), and won't be visible on the channel monitor."

But for me nothing happens if i change the "servo-center" . The servo is not moving

Can somebody confirm this?

**Comment by ajjjjjjjj** [comment]
Fixed for AFHDS2A.
