### ISSUE TITLE
Not working telemetry without RSSI but with valid TRSS

### ISSUE THREAD

**Issue by Snekovo** [OpenI6X/opentx#412]
I have CROSSOVER Telemetry RX FR7012-A2 (AFHDS 2A)
does not send RSSI only TRSS

telemetry correctly displays A3 drive battery voltage

The problems are.. that when trying to set up an alarm for low voltage in the logical switches section, picking A3 from the list of variables and comparing to a set value of (for example) 8.4v using the a<x function, the switch is never made...as if A3 doesn't exist.. also possibly connected is that the telemetry screen shows the datza and bar graphs for A3 and TRSS correctly, but a message flashes at the bottom of the screen "NO DATA"...

OpenI6X expects an RSSI value to be received and considers the lack of that as "no valid telemetry"

Please correct that OpenI6X knows when it receives TRSS that it should also work with telemetry 

Thank you

**Comment by ajjjjjjjj** [comment]
Can you show picture of telemetry screen with all sensors?

**Comment by Snekovo** [comment]
> Can you show picture of telemetry screen with all sensors?

![20240731_131849_th](https://github.com/user-attachments/assets/e7ad389f-525f-4061-941e-c7f35959ab16)
![20240731_131656_th](https://github.com/user-attachments/assets/b04db36e-aace-43d1-a5f7-37fa1c7923f7)
![20240731_131719_th](https://github.com/user-attachments/assets/293577ac-99d1-45c3-921e-13ae87e78a02)
