### ISSUE TITLE
Is it possible to have USB-Serial for Telemetry mirror?

### ISSUE THREAD

**Issue by Menginventor** [OpenI6X/opentx#415]
For recent version, the remote can interface via USB port in 2-mode, storage mode and Joytick mode. Is it possible to add the third mode as USB Serial?
Normally STM32 USB can be configured as USB-Serial so we can use telemetry mirror to PC easily and neat without additional wiring.

**Comment by ajjjjjjjj** [comment]
It is possible but requires some flash space. 
Theoretically it could be implemented as a on/off feature and used by disabling something else during compilation to fit into flash space.

**Comment by Menginventor** [comment]
May I ask for feature request on this one?

**Comment by robante15** [comment]
It would be interesting, as it would allow telemetry to be obtained from the PC, and applications to be developed to function more like a ground station.

**Comment by ajjjjjjjj** [comment]
> It would be interesting, as it would allow telemetry to be obtained from the PC, and applications to be developed to function more like a ground station.

It is already possible using UART to USB converters.
