### ISSUE TITLE
Windows 11 pro (AMD) A request for the USB device descriptor failed.

### ISSUE THREAD

**Issue by angelosne** [OpenI6X/opentx#418]
When I connect it as a usb controller it does not recognize it . I have seen two different reasons. See screenshots
With original firmware I didn't have a problem so I guess it should be on the FW side

1. Connect USB to pc
2. Select controller as USB Joystick

**Expected behavior**
Windows recognize the device as a controller

**Screenshots**
![error](https://github.com/user-attachments/assets/235956e6-4e7f-4213-88d4-119b2a3d6734)
![error2](https://github.com/user-attachments/assets/052a636c-d87d-4716-a014-8ea48fdff7c3)

**General information**
 - OpenI6X version 1.11.1
 - Hardware , the usb cable that came with the controller

**Comment by ajjjjjjjj** [comment]
Can you test on this build?
[opentx-i6x-1.11.1-en.zip](https://github.com/user-attachments/files/17083221/opentx-i6x-1.11.1-en.zip)

**Comment by angelosne** [comment]
I have already upload this FW but I haven't test it on my pc yet. I will let you know when I will test it! Thank you

**Comment by angelosne** [comment]
> @angelosne, can you test on this build? [opentx-i6x-1.11.1-en.zip](https://github.com/user-attachments/files/17083221/opentx-i6x-1.11.1-en.zip)

I just test it. Same thing happens.

**Comment by ajjjjjjjj** [comment]
Please test on 1.12.0, it should be finally fixed.

**Comment by angelosne** [comment]
Congrats!! It's fixed! Thank you very much!
Now I open the joystick settings on WIN 11  and I can see this 
![fs-i6x](https://github.com/user-attachments/assets/4a48f18a-a772-43ab-a5fa-4e32fdb24f8f)

Left joystick vertical = Z axis
Left joystick horizontal = X Rotation
Right joystick = Y Axis/Y Axis rectangle
All switches work from left to right 1-4
VR A = Slider

I do not see VR B change anything. Is something that I have to setup?

**Comment by angelosne** [comment]
Yes it is working. It was my mistake because I do not know how to set it up! 
All good now! Thank you
