### ISSUE TITLE
INPUTS context menu broken

### ISSUE THREAD

**Issue by valekrus** [OpenI6X/opentx#433]
**Describe the bug**
Contex menu is invisible at the INPUTS menu. When you long press ENTER (OK) on the input row you can't see the context menu (with edit/move/delete etc), but the actions work (just try to delete input row by long pressing OK, DOWN x5, OK). 

**To Reproduce**
1. Go to 'INPUTS' menu
2. go down at any row
3. Long press on 'ENTER' (OK)
4. You can't see the context menu, but it works!

**Expected behavior**
On OpenTX 1.11.1 (AFAIK) it was working correctly

**General information**
 - OpenI6X version (e.g. 1.12.0)

**Comment by ajjjjjjjj** [comment]
Confirmed, working on this.
