### ISSUE TITLE
Factory reset is required when a new version changes storage format

### ISSUE THREAD

**Issue by marianomd** [OpenI6X/opentx#80]
Start using eeprom conversions

**Comment by ajjjjjjjj** [comment]
This is actually top priority because of eeprom issues it causes.

**Comment by marianomd** [comment]
It would be great to use something similar to what EdgeTX uses: https://github.com/EdgeTX/edgetx/tree/main/radio/src/storage/conversions/yaml

**Comment by ajjjjjjjj** [comment]
yaml is more verbose so requires SDCard. This is possible with replacing FAT library with much lighter Petit FAT.

**Comment by ajjjjjjjj** [comment]
Since: eeprom format is pretty much established, checks are added for accidental change , no changes are planned (at least for now) and no one contributed to this for years, i'm closing it as stale and not useful for now.
