### ISSUE TITLE
About external RF module power on pin signal

### ISSUE THREAD

**Issue by whqsz** [OpenI6X/opentx#82]
quote:
// External Module
#define EXTMODULE_PWR_GPIO            GPIOC
#define EXTMODULE_PWR_GPIO_PIN        GPIO_Pin_9  // PC.09

PC9 pad in the definition of the target file is the open pin of the external RF module. The RF module is off or on in the model menu, but the pC9 level does not change in the actual measurement. What's the problem?

**Comment by ajjjjjjjj** [comment]
What version are you running?
Power toggling radio after change and ensuring that settings were saved enforces correct pin state?

**Comment by whqsz** [comment]
> What version are you running? Power toggling radio after change and ensuring that settings were saved enforces correct pin state?
newest v1.1.0 firmware
Because the target has a function pin defined, it is trying, but it is not sure whether it is valid.

**Comment by whqsz** [comment]
Whether the external switch option is off or on, the pC9 solder joint is always low.

I'm not sure whether it's a project bug or my own hardware problem

**Comment by ajjjjjjjj** [comment]
It looks like regression because it was working after power toggle.

**Comment by marianomd** [comment]
When implemented ppm in I worked around code related to this. I tried not to break anything but seems I did.

**Comment by ajjjjjjjj** [comment]
This is fixed but to power off you will need to power toggle the radio.

**Comment by zenghr2188** [comment]
Has the problem of pC9 pad switch output not been solved?

**Comment by ajjjjjjjj** [comment]
As you see in previous comment it is solved with a small issue - power toggle radio after settings save to force module off state. Powering on works perfect.

**Comment by zenghr2188** [comment]
Theoretically, it is realized in this way, but the reality is that pC9 pad has no level change and has always been low level.

**Comment by ajjjjjjjj** [comment]
No it was not, please do not share false information. Have you tested on latest master?

**Comment by ajjjjjjjj** [comment]
I've tested it on release 1.2.0 - works as described.

**Comment by zenghr2188** [comment]
When the external module uses ppm protocol, pC9 can work normally. I use crsf protocol. PC9 cannot work normally and has no high-level output.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "OpenI6X/opentx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月16日(星期天) 凌晨1:17
***@***.***&gt;;
抄送:&nbsp;"囂賬\~浩 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [OpenI6X/opentx] About external RF module power on pin signal (Issue #82)





 
I've tested it on release 1.2.0 - works as described.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ajjjjjjjj** [comment]
@zenghr2188 this is tested by me and it works. Show how do you connect it.
