### ISSUE TITLE
Compilation fails: missing string

### ISSUE THREAD

**Issue by wimalopaan** [OpenI6X/opentx#89]
I use the following cmake line:

cmake -DUSB_SERIAL=OFF -DGVARS=NO -DLUA_COMPILER=NO -DMULTIMODULE=NO -DDEBUG=NO -DHELI=OFF -DTRANSLATIONS=DE -DPCB=I6X -DOVERRIDE_CHANNEL_FUNCTION=OF
F -DDISABLE_COMPANION=YES ..

but I get the following error:

/home/lmeier/Projekte/openi6x/opentx/radio/src/telemetry/crossfire.cpp:42:21: error: 'ZSTR_BATT_PERCENT' was not declared in this scope; did you mean 'ZSTR_BATT1_CURRENT'?
42 | {BATTERY_ID, 3, ZSTR_BATT_PERCENT, UNIT_PERCENT, 0},
| ^~~~~~~~~~~~~~~~~
| ZSTR_BATT1_CURRENT
make[2]: *** [radio/src/CMakeFiles/firmware.dir/build.make:370: radio/src/CMakeFiles/firmware.dir/telemetry/crossfire.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:493: radio/src/CMakeFiles/firmware.dir/all] Fehler 2

**Comment by ajjjjjjjj** [comment]
I was doing changes with only english translation in mind to speed up development. I guess now we have to keep all the languages in sync.

**Comment by wimalopaan** [comment]
Fixed this by myself, only locally for the moment ...

**Comment by wimalopaan** [comment]
Here is a patch:

[de.patch.gz](https://github.com/OpenI6X/opentx/files/7774535/de.patch.gz)

**Comment by ajjjjjjjj** [comment]
Thanks, I have updated even more.
Can you test it and let me know? https://github.com/OpenI6X/opentx/pull/100

**Comment by wimalopaan** [comment]
Looks fine now!
